name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0

    - name: Build
      run: |
        pnpm add -g ember-cli
        pnpm install
        pnpm build
            - name: Upload a Build Artifact
    - name: Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: artifact-chrome
        path: dist/chrome
